### ISSUE TITLE
RuntimeError: Library cublasLt is not initialized

### ISSUE THREAD

**Issue by dawangcao** [MinusZoneAI/ComfyUI-Kolors-MZ#14]
torch version: 2.2.0+cu118
Symbol cudaLaunchKernel not found in C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\cudart64_65.dll
!!! Exception during processing!!! Library cublasLt is not initialized
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\ComfyUI-aki-v1\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\ComfyUI-aki-v1\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\ComfyUI-aki-v1\custom_nodes\ComfyUI-Kolors-MZ\__init__.py", line 64, in load_chatglm3
    return mz_kolors_core.MZ_ChatGLM3Loader_call(kwargs)
  File "D:\ComfyUI-aki-v1\custom_nodes\ComfyUI-Kolors-MZ\mz_kolors_core.py", line 113, in MZ_ChatGLM3Loader_call
    text_encoder.quantize(4)
  File "D:\ComfyUI-aki-v1\custom_nodes\ComfyUI-Kolors-MZ\chatglm3\modeling_chatglm.py", line 852, in quantize
    quantize(self.encoder, weight_bit_width)
  File "D:\ComfyUI-aki-v1\custom_nodes\ComfyUI-Kolors-MZ\chatglm3\quantization.py", line 155, in quantize
    layer.self_attention.query_key_value = QuantizedLinear(
  File "D:\ComfyUI-aki-v1\custom_nodes\ComfyUI-Kolors-MZ\chatglm3\quantization.py", line 139, in __init__
    self.weight = compress_int4_weight(self.weight)
  File "D:\ComfyUI-aki-v1\custom_nodes\ComfyUI-Kolors-MZ\chatglm3\quantization.py", line 78, in compress_int4_weight
    kernels.int4WeightCompression(
  File "D:\ComfyUI-aki-v1\python\lib\site-packages\cpm_kernels\kernels\base.py", line 48, in __call__
    func = self._prepare_func()
  File "D:\ComfyUI-aki-v1\python\lib\site-packages\cpm_kernels\kernels\base.py", line 40, in _prepare_func
    self._module.get_module(), self._func_name
  File "D:\ComfyUI-aki-v1\python\lib\site-packages\cpm_kernels\kernels\base.py", line 23, in get_module
    Device(curr_device).use()   # force initialize context
  File "D:\ComfyUI-aki-v1\python\lib\site-packages\cpm_kernels\device\__init__.py", line 152, in use
    self._device.use()
  File "D:\ComfyUI-aki-v1\python\lib\site-packages\cpm_kernels\device\__init__.py", line 120, in use
    self.cublasLtHandle = cublaslt.cublasLtCreate()
  File "D:\ComfyUI-aki-v1\python\lib\site-packages\cpm_kernels\library\base.py", line 72, in wrapper
    raise RuntimeError("Library %s is not initialized" % self.__name)
RuntimeError: Library cublasLt is not initialized

**Comment by wailovet** [comment]
> torch version: 2.2.0+cu118 Symbol cudaLaunchKernel not found in C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\cudart64_65.dll !!! Exception during processing!!! Library cublasLt is not initialized Traceback (most recent call last): File "D:\ComfyUI-aki-v1\execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) File "D:\ComfyUI-aki-v1\execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) File "D:\ComfyUI-aki-v1\execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) File "D:\ComfyUI-aki-v1\custom_nodes\ComfyUI-Kolors-MZ__init__.py", line 64, in load_chatglm3 return mz_kolors_core.MZ_ChatGLM3Loader_call(kwargs) File "D:\ComfyUI-aki-v1\custom_nodes\ComfyUI-Kolors-MZ\mz_kolors_core.py", line 113, in MZ_ChatGLM3Loader_call text_encoder.quantize(4) File "D:\ComfyUI-aki-v1\custom_nodes\ComfyUI-Kolors-MZ\chatglm3\modeling_chatglm.py", line 852, in quantize quantize(self.encoder, weight_bit_width) File "D:\ComfyUI-aki-v1\custom_nodes\ComfyUI-Kolors-MZ\chatglm3\quantization.py", line 155, in quantize layer.self_attention.query_key_value = QuantizedLinear( File "D:\ComfyUI-aki-v1\custom_nodes\ComfyUI-Kolors-MZ\chatglm3\quantization.py", line 139, in **init** self.weight = compress_int4_weight(self.weight) File "D:\ComfyUI-aki-v1\custom_nodes\ComfyUI-Kolors-MZ\chatglm3\quantization.py", line 78, in compress_int4_weight kernels.int4WeightCompression( File "D:\ComfyUI-aki-v1\python\lib\site-packages\cpm_kernels\kernels\base.py", line 48, in **call** func = self._prepare_func() File "D:\ComfyUI-aki-v1\python\lib\site-packages\cpm_kernels\kernels\base.py", line 40, in _prepare_func self._module.get_module(), self._func_name File "D:\ComfyUI-aki-v1\python\lib\site-packages\cpm_kernels\kernels\base.py", line 23, in get_module Device(curr_device).use() # force initialize context File "D:\ComfyUI-aki-v1\python\lib\site-packages\cpm_kernels\device__init__.py", line 152, in use self._device.use() File "D:\ComfyUI-aki-v1\python\lib\site-packages\cpm_kernels\device__init__.py", line 120, in use self.cublasLtHandle = cublaslt.cublasLtCreate() File "D:\ComfyUI-aki-v1\python\lib\site-packages\cpm_kernels\library\base.py", line 72, in wrapper raise RuntimeError("Library %s is not initialized" % self.__name) RuntimeError: Library cublasLt is not initialized


参考: https://github.com/THUDM/ChatGLM-6B/issues/465
试一下更新cuda到12.1版本能否解决
