### ISSUE TITLE
RuntimeError: Only Tensors of floating point and complex dtype can require gradients

### ISSUE THREAD

**Issue by klossm** [MinusZoneAI/ComfyUI-Kolors-MZ#6]
显卡是1070ti 8G，这个报错不知道是否和1070ti的显卡兼容性有关，
下载完整的chatglm文本模型然后选择所有的量化选项运行没有任何报错问题，但是载入已经量化好的模型时候会出现错误，chatglm3-8bit.safetensors和chatglm3-4bit.safetensors都试过都是如此，问过其他人有的也有类似错误，但是也有正常的，问过正常运行的人，他的touch版本和我的一样也是2.3.0，xformers依赖不管有没有安装都是报错，comfyui的启动参数不管有没有 --force-fp16 都是如此。主要是想省点硬盘空间，所以想用量化后的模型载入。

下面是完整的报错信息：

Traceback (most recent call last):
File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper\nodes.py", line 122, in loadmodel
text_encoder.quantize(4)
File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper\kolors\models\modeling_chatglm.py", line 852, in quantize
quantize(self.encoder, weight_bit_width)
File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper\kolors\models\quantization.py", line 155, in quantize
layer.self_attention.query_key_value = QuantizedLinear(
File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper\kolors\models\quantization.py", line 141, in init
self.weight = Parameter(self.weight.to(device), requires_grad=False)
File "L:\stable-diffusion\venv\lib\site-packages\torch\nn\modules\module.py", line 1726, in setattr
self.register_parameter(name, value)
File "L:\stable-diffusion\venv\lib\site-packages\accelerate\big_modeling.py", line 105, in register_empty_parameter
module._parameters[name] = param_cls(module._parameters[name].to(device), **kwargs)
File "L:\stable-diffusion\venv\lib\site-packages\torch\nn\parameter.py", line 40, in new
return torch.Tensor._make_subclass(cls, data, requires_grad)
RuntimeError: Only Tensors of floating point and complex dtype can require gradients

**Comment by linesword** [comment]
同样的问题，你解决了吗？ @klossm

**Comment by wailovet** [comment]
> 同样的问题，你解决了吗？ @klossm

这部分代码来自KwaiKolorsWrapper仓库,我猜可能和torch版本或者环境有关,试一下更新accelerate到最新版本或者切换torch版本看看有没有改善

**Comment by iso223** [comment]
已解决

**Comment by amberfay** [comment]
> 已解决

怎么解决的
