### ISSUE TITLE
ERROR: Could not detect model type of: E:\IMAGE\ComfyUI_master\ComfyUI\models\checkpoints\kolors_fp16.safetensors

### ISSUE THREAD

**Issue by whmc76** [MinusZoneAI/ComfyUI-Kolors-MZ#61]
got prompt
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing!!! ERROR: Could not detect model type of: E:\IMAGE\ComfyUI_master\ComfyUI\models\checkpoints\kolors_fp16.safetensors
Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI_master\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_master\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_master\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Kolors-MZ\__init__.py", line 158, in load_checkpoint
    return mz_kolors_core.MZ_KolorsCheckpointLoaderSimple_call(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Kolors-MZ\mz_kolors_core.py", line 222, in MZ_KolorsCheckpointLoaderSimple_call
    out = comfy.sd.load_checkpoint_guess_config(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_master\ComfyUI\comfy\sd.py", line 506, in load_checkpoint_guess_config
    raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))
RuntimeError: ERROR: Could not detect model type of: E:\IMAGE\ComfyUI_master\ComfyUI\models\checkpoints\kolors_fp16.safetensors

#68 [MZ_KolorsCheckpointLoaderSimple]: 0.04s

**Comment by whmc76** [comment]
<img width="1219" alt="1722182949103" src="https://github.com/user-attachments/assets/92b368a5-5487-45ed-aa0a-3e936dd3f7f4">

这两个模型都不能正确加载

![image](https://github.com/user-attachments/assets/6356b4ff-0cbd-4ec7-a23d-777b268c9216)

**Comment by wailovet** [comment]
> <img alt="1722182949103" width="1219" src="https://private-user-images.githubusercontent.com/129386342/352851961-92b368a5-5487-45ed-aa0a-3e936dd3f7f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxOTA5NjIsIm5iZiI6MTcyMjE5MDY2MiwicGF0aCI6Ii8xMjkzODYzNDIvMzUyODUxOTYxLTkyYjM2OGE1LTU0ODctNDVlZC1hYTBhLTNlOTM2ZGQzZjdmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQxODE3NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzFkYjQwNjczNzNhY2U5M2VjNmM2NzUwN2ZlMTczMDdhZTk1ZWM0MDAwMTYyZjg3MTZjODFlZDNlNmRjZTJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0sKmziX4-kZDD4kn1NQSe3Z0ztWtkTGRB7J6Yz1VbSc">
> 这两个模型都不能正确加载
> 
> ![image](https://private-user-images.githubusercontent.com/129386342/352852006-6356b4ff-0cbd-4ec7-a23d-777b268c9216.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxOTA5NjIsIm5iZiI6MTcyMjE5MDY2MiwicGF0aCI6Ii8xMjkzODYzNDIvMzUyODUyMDA2LTYzNTZiNGZmLTBjYmQtNGVjNy1hMjNkLTc3N2IyNjhjOTIxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQxODE3NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTdmZmNlMTU0ZjA3YTdiMjdhZjMzZTljMTM5ZjZhZjZhNGQ4ZjRhYzNiYWIxNzBiM2U3ZGNiZDRjYmRkNTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8hve-pPexyE0tyKpVALGCdCAN02r0KqCTm736qa_uyA)

用unet加载器

**Comment by whmc76** [comment]
好滴



---Original---
From: ***@***.***&gt;
Date: Mon, Jul 29, 2024 02:19 AM
To: ***@***.***&gt;;
Cc: "Cyber Dick ***@***.******@***.***&gt;;
Subject: Re: [MinusZoneAI/ComfyUI-Kolors-MZ] ERROR: Could not detect modeltype of:E:\IMAGE\ComfyUI_master\ComfyUI\models\checkpoints\kolors_fp16.safetensors(Issue #61)




 
用unet加载器
