### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by chaorenai** [MinusZoneAI/ComfyUI-Kolors-MZ#65]
What comes up when you are using the official ControlNet model:

Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\nodes.py", line 720, in load_controlnet
    controlnet = comfy.controlnet.load_controlnet(controlnet_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\controlnet.py", line 384, in load_controlnet
    diffusers_keys = comfy.utils.unet_to_diffusers(controlnet_config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\utils.py", line 188, in unet_to_diffusers
    if "num_res_blocks" not in unet_config:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

Prompt executed in 24.43 seconds

**Comment by chaorenai** [comment]
Is it a bug in the node? How can I use the official ControlNnet model?

**Comment by chaorenai** [comment]
![workflow_controlnet](https://github.com/user-attachments/assets/de22a5b6-51e1-4104-91ad-745272e80051)

Is there some problems with the official workflow, that it shows error messages all the time?

**Comment by wailovet** [comment]
Reference:  examples/workflow_official_controlnet.png

**Comment by xyr4life** [comment]
I have met the same problem, is there any solution?
